/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'devipad.tripathy' at '3/17/19 6:02 PM' with Gradle 2.9
 *
 * @author devipad.tripathy, @date 3/17/19 6:02 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
